// ===================== AI VOICE ASSISTANT (English / Telugu / Hindi) =====================
// Uses Web Speech API (SpeechRecognition + SpeechSynthesis) for voice in/out.
// Answers are generated by a lightweight keyword-matching knowledge base.
// In production, replace answerQuery() with a call to your backend AI endpoint
// (e.g. POST /api/assistant which calls an LLM with the village knowledge base).

const voicePanel = document.getElementById('voicePanel');
const voiceChat = document.getElementById('voiceChat');
const voiceLangSelect = document.getElementById('voiceLang');

document.getElementById('voiceBtn').addEventListener('click', ()=>{
  voicePanel.classList.add('show');
  if(voiceChat.children.length===0) botSay(greet());
});
document.getElementById('closeVoice').addEventListener('click', ()=> voicePanel.classList.remove('show'));

function greet(){
  const lang = voiceLangSelect.value;
  if(lang==='te-IN') return "నమస్కారం! నేను మీ గ్రామ సహాయకుడిని. పథకాలు, భూమి సేవలు, వ్యవసాయం, ఉద్యోగాలు గురించి అడగండి.";
  if(lang==='hi-IN') return "नमस्ते! मैं आपका ग्राम सहायक हूँ। योजनाओं, भूमि सेवाओं, कृषि या नौकरियों के बारे में पूछें।";
  return "Hello! I'm your AI Village Assistant. Ask me about schemes, land services, agriculture, jobs, or village documents.";
}

function userSay(text){
  const div = document.createElement('div');
  div.className = 'voice-msg user';
  div.textContent = text;
  voiceChat.appendChild(div);
  voiceChat.scrollTop = voiceChat.scrollHeight;
}
function botSay(text){
  const div = document.createElement('div');
  div.className = 'voice-msg bot';
  div.textContent = text;
  voiceChat.appendChild(div);
  voiceChat.scrollTop = voiceChat.scrollHeight;
  speak(text);
}

// ---- Speech synthesis (bot speaks reply) ----
function speak(text){
  if(!('speechSynthesis' in window)) return;
  const utter = new SpeechSynthesisUtterance(text);
  utter.lang = voiceLangSelect.value;
  speechSynthesis.cancel();
  speechSynthesis.speak(utter);
}

// ---- Speech recognition (mic input) ----
let recognition = null;
const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
if(SpeechRecognition){
  recognition = new SpeechRecognition();
  recognition.continuous = false;
  recognition.interimResults = false;
}
document.getElementById('micBtn').addEventListener('click', ()=>{
  if(!recognition){
    showToast('Voice recognition not supported in this browser. Please type instead.');
    return;
  }
  recognition.lang = voiceLangSelect.value;
  recognition.start();
  showToast('Listening...');
});
if(recognition){
  recognition.onresult = (e)=>{
    const transcript = e.results[0][0].transcript;
    handleUserInput(transcript);
  };
  recognition.onerror = ()=> showToast('Could not hear you, please try again.');
}

document.getElementById('sendVoiceText').addEventListener('click', ()=>{
  const input = document.getElementById('voiceTextInput');
  if(input.value.trim()){
    handleUserInput(input.value.trim());
    input.value='';
  }
});
document.getElementById('voiceTextInput').addEventListener('keydown', e=>{
  if(e.key==='Enter') document.getElementById('sendVoiceText').click();
});

function handleUserInput(text){
  userSay(text);
  setTimeout(()=> botSay(answerQuery(text)), 400);
}

// ===================== KNOWLEDGE BASE / RULE-BASED ANSWERS =====================
function answerQuery(q){
  const lang = voiceLangSelect.value;
  const t = q.toLowerCase();

  const kb = [
    { keys:["rythu bharosa","రైతు భరోసా"],
      en:"Rythu Bharosa gives ₹10,000 per acre per year to farming families. Apply with your Pattadar Passbook and Aadhaar on the Agriculture page.",
      te:"రైతు భరోసా పథకం ద్వారా ఎకరానికి ఏటా ₹10,000 సహాయం అందిస్తారు. పట్టాదార్ పాస్‌బుక్, ఆధార్‌తో దరఖాస్తు చేసుకోండి.",
      hi:"रायथु भरोसा योजना में किसानों को प्रति एकड़ ₹10,000 सालाना सहायता मिलती है। पट्टादार पासबुक और आधार से आवेदन करें।" },
    { keys:["pattadar","passbook","పాస్‌బుక్"],
      en:"You can apply for or download your Pattadar Passbook through Dharani portal under Land Services.",
      te:"మీరు ధరణి పోర్టల్ ద్వారా పట్టాదార్ పాస్‌బుక్ కోసం దరఖాస్తు చేసుకోవచ్చు లేదా డౌన్‌లోడ్ చేసుకోవచ్చు.",
      hi:"आप धरणी पोर्टल के माध्यम से पट्टादार पासबुक के लिए आवेदन कर सकते हैं।" },
    { keys:["aadhaar","ఆధార్"],
      en:"For Aadhaar enrollment, updates, or corrections, visit the Village Services page and nearest MeeSeva/Aadhaar Seva Kendra.",
      te:"ఆధార్ నమోదు, మార్పులు కోసం గ్రామ సేవలు పేజీలోని మీసేవ కేంద్రాన్ని సందర్శించండి.",
      hi:"आधार पंजीकरण या सुधार के लिए ग्राम सेवा पृष्ठ पर नज़दीकी मीसेवा केंद्र देखें।" },
    { keys:["job","ఉద్యోగం","नौकरी"],
      en:"Check the Jobs page for Government jobs, MGNREGS work, private jobs, and skill development programs.",
      te:"ప్రభుత్వ ఉద్యోగాలు, MGNREGS పని, ప్రైవేట్ ఉద్యోగాల కోసం ఉద్యోగాలు పేజీని చూడండి.",
      hi:"सरकारी नौकरी, मनरेगा कार्य और कौशल विकास के लिए नौकरियां पेज देखें।" },
    { keys:["certificate","ధృవీకరణ","प्रमाण"],
      en:"Income, Caste, Birth, Death and Residence certificates can all be applied for via MeeSeva under Village Services.",
      te:"ఆదాయ, కుల, జనన, మరణ, నివాస ధృవీకరణ పత్రాలను మీసేవ ద్వారా పొందవచ్చు.",
      hi:"आय, जाति, जन्म, मृत्यु और निवास प्रमाणपत्र मीसेवा के माध्यम से प्राप्त किए जा सकते हैं।" },
    { keys:["scheme","పథకం","योजना"],
      en:"You can browse all Central and Telangana state schemes with eligibility and documents on the Schemes page.",
      te:"కేంద్ర, తెలంగాణ ప్రభుత్వ పథకాలను అన్నింటినీ పథకాలు పేజీలో చూడవచ్చు.",
      hi:"सभी केंद्र और तेलंगाना राज्य योजनाएं स्कीम्स पेज पर देखें।" },
    { keys:["weather","వాతావరణం","मौसम"],
      en:"Today's weather and market prices are shown on the Agriculture page.",
      te:"నేటి వాతావరణం, మార్కెట్ ధరలు వ్యవసాయం పేజీలో ఉన్నాయి.",
      hi:"आज का मौसम और बाजार भाव कृषि पेज पर देखें।" },
    { keys:["complaint","ఫిర్యాదు","शिकायत"],
      en:"You can submit and track complaints about roads, water, or electricity from the Complaint Portal page.",
      te:"రోడ్లు, నీరు, విద్యుత్ గురించి ఫిర్యాదులను ఫిర్యాదుల పోర్టల్ పేజీలో సమర్పించవచ్చు.",
      hi:"सड़क, पानी या बिजली से जुड़ी शिकायतें कंप्लेंट पोर्टल पेज पर दर्ज करें।" },
    { keys:["emergency","అత్యవసరం","आपातकाल"],
      en:"For emergencies: Police 100, Fire 101, Ambulance 108. Full list available on the Emergency page.",
      te:"అత్యవసర పరిస్థితుల్లో: పోలీసు 100, అగ్నిమాపక దళం 101, అంబులెన్స్ 108.",
      hi:"आपातकाल में: पुलिस 100, फायर 101, एम्बुलेंस 108।" },
  ];

  for(const item of kb){
    if(item.keys.some(k=>t.includes(k))){
      return lang==='te-IN' ? item.te : lang==='hi-IN' ? item.hi : item.en;
    }
  }
  if(lang==='te-IN') return "క్షమించండి, నాకు అది అర్థం కాలేదు. దయచేసి పథకాలు, భూమి సేవలు, వ్యవసాయం లేదా ధృవీకరణ పత్రాల గురించి అడగండి.";
  if(lang==='hi-IN') return "क्षमा करें, मुझे समझ नहीं आया। कृपया योजनाओं, भूमि सेवाओं या प्रमाणपत्रों के बारे में पूछें।";
  return "Sorry, I didn't understand that. Try asking about schemes, land services, agriculture, jobs, or certificates.";
}

voiceLangSelect.addEventListener('change', ()=>{
  if(voiceChat.children.length>0) botSay(greet());
});
